## 1.將信用卡版討論文章下載存入到自己電腦

In [53]:
!wget https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv

--2020-07-26 20:24:05--  https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv
正在查找主機 raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.64.133, 151.101.192.133, ...
正在連接 raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... 連上了。
已送出 HTTP 要求，正在等候回應... 200 OK
長度: 3688 (3.6K) [text/plain]
儲存到：`creditcard_titles.csv'

creditcard_titles.c 100%[===================>]   3.60K  --.-KB/s  於 0s         

2020-07-26 20:24:05 (9.77 MB/s) - 已儲存 `creditcard_titles.csv' [3688/3688]



In [54]:
import pandas as pd

In [90]:
df = pd.read_csv('./creditcard_titles.csv',index_col=False,encoding='utf-8')

In [91]:
df

Unnamed: 0                        title
0            0                 [問題] 富邦j卡新戶禮
1            1  [心得] 玉山 u bear/pi 核卡、台新富邦調額
2            2  Re: [情報] 中信ANA消費應援哩活動(加碼名額)
3            3               [問題] 台新@gogo調額
4            4            [心得] 渣打現金回饋御璽卡 未過
..         ...                          ...
66          66             [心得] 台新GoGo卡 已核卡
67          67         [心得] 玉山Pi卡&花旗現金回饋卡申請
68          68                [問題] 關於刷卡金額限制
69          69                 [問題] 三倍券刷卡通路
70          70           [心得] 聯邦賴點卡換卡（附三代卡面

[71 rows x 2 columns]

## 2.請讀取該檔案，並將所有標題讀入成titles 的list

In [104]:
titles  = df['title'].tolist()

In [105]:
titles 

['[問題] 富邦j卡新戶禮',
 '[心得] 玉山 u bear/pi 核卡、台新富邦調額',
 'Re: [情報] 中信ANA消費應援哩活動(加碼名額)',
 '[問題] 台新@gogo調額',
 '[心得] 渣打現金回饋御璽卡 未過',
 'Re: [閒聊] 本月玉山Only最新抽獎回饋',
 '[情報] 台新也有3倍券 刷50換150 分眾簡訊',
 '[心得] 富邦J卡 星展炫晶 永豐幣倍 國泰Costco 核卡',
 'Re: [情報] 玉山pi分眾屈臣氏促刷活動',
 '[新聞] 為家人上網預購振興券 刷聯邦卡回饋2％',
 '[問題] apple pay算實體刷卡後續疑問',
 '[心得] 神奇的匯豐及渣打新光星展凱基 核卡心得',
 '[心得] 渣打現金回饋御璽卡 核卡（Money101）',
 '[心得] 新光 凱基 新戶核卡',
 '[心得] 渣打現金回饋御璽卡 核卡(money101)',
 '[心得] 中信 LinePay 商務御璽(城市樂跑) 核卡',
 '[問題] 有人信用卡不是用掛號寄來的嗎?',
 '[心得] 渣打現金回饋/富邦J 核卡',
 'Re: [閒聊] 新光悠遊晶緻卡新戶/回饋活動懶人包整理',
 '[問題] 信用卡繳稅後如何付款',
 '[心得] 富邦j卡未核',
 '[心得] 富邦悍將聯名卡核卡',
 '[問題] 申請信用卡的財力證明可以用土地謄本嗎？',
 '[心得] 渣打現金回饋御璽卡 核卡',
 '[心得] 元大鑽金Hello Kitty聯名卡',
 '[心得] 大滿貫之路 匯豐現金 合庫卡娜核卡(18家)',
 'Re: [問題] 請問109年燃料費,有信用卡可回饋嗎?',
 'Re: [情報] 「卡莉嗨」信用卡回饋查詢app',
 '[問題] 玉山wallet 線上繳費疑問',
 '[問題] 聯邦Line Pay Money繳卡費2%',
 '[新聞] 三倍券15日上路 經濟部推數位券、紙本券 ',
 '[心得] 玉山Ubear悠遊聯名卡(黃)高雄Youbike2.0',
 'Re: [心得] U Bear 不佔額度分期回饋',
 '[心得] 渣打現金回饋御璽卡 核卡',
 '[閒聊] 笑死!三倍券綁信用卡最不划算!改換紙本!',
 'Re: [閒聊] 笑死!三倍券綁信用卡最不划算!改換紙本!',
 '[問題

In [106]:
type(titles)

list

## 3.請使用sklearn 將資料轉換為詞頻矩陣(CountVectorizer)

In [121]:
from sklearn.feature_extraction.text import CountVectorizer

In [122]:
credit_jieba = []

In [123]:
for i in titles:
    credit_jieba.append(' '.join(jieba.cut(i)))

In [125]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(credit_jieba)

In [129]:
X

<71x187 sparse matrix of type '<class 'numpy.int64'>'
	with 445 stored elements in Compressed Sparse Row format>

In [131]:
print(vectorizer.get_feature_names())

['10', '109', '15', '150', '18', '2020', '50', 'ana', 'app', 'apple', 'bear', 'costco', 'gogo', 'happy', 'hello', 'icash', 'kitty', 'line', 'linepay', 'money', 'money101', 'only', 'pay', 'pi', 're', 'ubear', 'ubereat', 'wallet', 'youbike2', '三代', '上市', '上網', '上路', '下半年', '世界', '中信', '中油', '付款', '使用', '促刷', '信用卡', '倍券', '停車', '優惠', '兆豐', '全新', '凱基', '分期', '分眾', '划算', '列入', '刷卡', '刷聯邦卡', '券搭', '券綁', '加碼', '助理', '匯豐', '卡娜', '卡新', '卡莉', '卡費', '卡面', '可以', '台哥大', '台新', '合庫', '名額', '售票', '商務', '商機', '問題', '嘟嘟房', '回饋', '國旅', '國泰', '土地', '城市', '外幣', '多家', '大滿貫', '大鑽', '太陽', '如何', '學貸', '學費', '家人', '寄來', '富邦', '實體', '寰宇', '小白', '屈臣氏', '幣倍', '幼兒園', '影城', '後續', '御璽', '御璽卡', '心得', '悍將', '悠遊', '情報', '感謝', '應援', '懶人包', '戶禮', '戶辦', '折抵', '抽獎', '指定', '振新', '振興', '掛號', '推薦', '推銷', '換卡', '改換', '整理', '數位', '新光', '新光三越', '新聞', '星展', '晶緻卡', '未核', '未過', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡', '燃料', '燃料費', '玉山', '現金', '現金袋', '申請', '疑問', '研究', '神奇', '笑死', '簡訊', '粉紅', '紙本', '經濟部

In [130]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

## 4.請使用sklearn 將資料轉換為TF-IDF矩陣(TfidfVectorizer)

In [135]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [136]:
credit_jieba

['[ 問題 ]   富邦 j 卡新 戶禮',
 '[ 心得 ]   玉山   u   bear / pi   核卡 、 台新 富邦 調額',
 'Re :   [ 情報 ]   中信 ANA 消費 應援 哩 活動 ( 加碼 名額 )',
 '[ 問題 ]   台新 @ gogo 調額',
 '[ 心得 ]   渣打 現金 回饋 御璽卡   未過',
 'Re :   [ 閒聊 ]   本 月 玉山 Only 最 新 抽獎 回饋',
 '[ 情報 ]   台新 也 有 3 倍券   刷 50 換 150   分眾 簡訊',
 '[ 心得 ]   富邦 J 卡   星展 炫晶   永豐 幣倍   國泰 Costco   核卡',
 'Re :   [ 情報 ]   玉山 pi 分眾 屈臣氏 促刷 活動',
 '[ 新聞 ]   為 家人 上網 預購 振興 券   刷聯邦卡 回饋 2 ％',
 '[ 問題 ]   apple   pay 算 實體 刷卡 後續 疑問',
 '[ 心得 ]   神奇 的 匯豐 及 渣打 新光 星展 凱基   核卡 心得',
 '[ 心得 ]   渣打 現金 回饋 御璽卡   核卡 （ Money101 ）',
 '[ 心得 ]   新光   凱基   新 戶 核卡',
 '[ 心得 ]   渣打 現金 回饋 御璽卡   核卡 ( money101 )',
 '[ 心得 ]   中信   LinePay   商務 御璽 ( 城市 樂跑 )   核卡',
 '[ 問題 ]   有 人 信用卡 不 是 用 掛號 寄來 的 嗎 ?',
 '[ 心得 ]   渣打 現金 回饋 / 富邦 J   核卡',
 'Re :   [ 閒聊 ]   新光 悠遊 晶緻卡 新 戶 / 回饋 活動 懶人包 整理',
 '[ 問題 ]   信用卡 繳稅 後 如何 付款',
 '[ 心得 ]   富邦 j 卡 未核',
 '[ 心得 ]   富邦 悍將 聯名 卡 核卡',
 '[ 問題 ]   申請 信用卡 的 財力 證明 可以 用 土地 謄本 嗎 ？',
 '[ 心得 ]   渣打 現金 回饋 御璽卡   核卡',
 '[ 心得 ]   元 大鑽 金 Hello   Kitty 聯名 卡',
 '[ 心得 ]   大滿貫 之 路   匯豐 現金   合庫 卡娜 核卡 

In [137]:
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(credit_jieba)

In [139]:
X_tfidf.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.42012981]])

In [141]:
X_tfidf.toarray()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.61395422,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.27563736, 0.        , 0.        , 0.     