In [46]:
sentences = ["How to format my hard disk", " Hard disk format problems "]

In [47]:
len(sentences)

2

In [48]:
words_set = []
for sentence in sentences:
    words = sentence.lower().split() 
    words_set = words_set + words
    #words_set.extend(words)

In [49]:
words_set

['how',
 'to',
 'format',
 'my',
 'hard',
 'disk',
 'hard',
 'disk',
 'format',
 'problems']

In [50]:
set(words_set)

{'disk', 'format', 'hard', 'how', 'my', 'problems', 'to'}

In [51]:
id_to_word = {}
word_to_id = {}
for idx,word in enumerate(set(words_set)):
    #print(idx,word)
    id_to_word[idx]=word
    word_to_id[word]=idx

In [52]:
id_to_word

{0: 'to', 1: 'how', 2: 'my', 3: 'problems', 4: 'format', 5: 'disk', 6: 'hard'}

In [53]:
word_to_id

{'to': 0, 'how': 1, 'my': 2, 'problems': 3, 'format': 4, 'disk': 5, 'hard': 6}

In [54]:
sorted(word_to_id.items(),key=lambda e:e[1],reverse=True)

[('hard', 6),
 ('disk', 5),
 ('format', 4),
 ('problems', 3),
 ('my', 2),
 ('how', 1),
 ('to', 0)]

In [55]:
import numpy as np

In [56]:
m  = np.zeros((len(sentences),len(word_to_id)))

In [57]:
m

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [58]:
m.shape

(2, 7)

In [61]:
for i,sentence in enumerate(sentences):
    for w  in sentence.lower().split():
        #print(w ,i, word_to_id[w])
        m[i,word_to_id[w]]=1

In [64]:
word_to_id['how']

1

In [62]:
m

array([[1., 1., 1., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

# Numpy

In [28]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [32]:
for i in range(0,len(a)):
    print(a[i]*b[i])

2
12
30
56
90


In [33]:
for rec in zip(a,b):
    print(rec)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [34]:
for i,j in zip(a,b):
    print(i*j)

2
12
30
56
90


In [35]:
type(a)

list

In [36]:
a

[1, 3, 5, 7, 9]

In [37]:
import numpy as np

In [43]:
na = np.array(a)
nb = np.array(b)

In [44]:
na + nb

array([ 3,  7, 11, 15, 19])

In [45]:
na * nb

array([ 2, 12, 30, 56, 90])

In [46]:
na = np.array([1,2,3,4,5])

In [47]:
na[0]

1

In [48]:
na[-1]

5

In [49]:
na > 3

array([False, False, False,  True,  True])

In [50]:
na[na>3]

array([4, 5])

In [51]:
na = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [52]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
na[0,0]

1

In [54]:
na[0,:]

array([1, 2, 3, 4, 5])

In [55]:
na[:,0]

array([1, 6])

In [56]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# Scikit-Learn 建立詞頻矩陣

fit : 產生結構 
fir_transform : 產生結構並轉換資料
transform : 轉換資料

In [60]:
content = ["How to format my hard disk", " Hard disk format problems "]

In [81]:
from sklearn.feature_extraction.text import CountVectorizer

In [82]:
vectorizer = CountVectorizer()

In [83]:
X = vectorizer.fit_transform(content)

In [84]:
X

<2x7 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [85]:
X.toarray()

array([[1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 0]])

In [86]:
vectorizer.get_feature_names()

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']

In [87]:
contents2 = ['i love hard disk']

In [88]:
X2 = vectorizer.transform(contents2)

In [89]:
X2.toarray()

array([[1, 0, 1, 0, 0, 0, 0]])

# 建立詞袋模型

In [65]:
contents = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
'Imaging databases can get huge.',
'Most imaging databases safe images permanently.',
'Imaging databases store images.',
'Imaging databases store images. Imaging databases store images. Imaging databases store images.']

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
vectorizer = CountVectorizer()

In [68]:
X = vectorizer.fit_transform(contents)

In [69]:
print(vectorizer.get_feature_names())

['about', 'actually', 'can', 'contains', 'databases', 'get', 'huge', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'safe', 'store', 'stuff', 'this', 'toy']


In [70]:
X

<5x24 sparse matrix of type '<class 'numpy.int64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [71]:
new_post = 'imaging databases'

In [72]:
new_post_vec = vectorizer.transform([new_post])

In [73]:
new_post_vec

<1x24 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [74]:
new_post_vec.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]])

In [75]:
import math

In [76]:
# enclidean distance 除於資料個數 /24
math.sqrt((((new_post_vec - X[0]).toarray())**2).sum() )

4.0

In [77]:
import scipy as sp

In [78]:
sp.linalg.norm((new_post_vec - X[0]).toarray())

4.0

In [79]:
def dist_raw(v1, v2): 
    delta = v1-v2
    return sp.linalg.norm(delta.toarray())

In [80]:
for i in range(5):
    d = dist_raw(X[i],new_post_vec)
    print(contents[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 4.0
Imaging databases can get huge. 1.7320508075688772
Most imaging databases safe images permanently. 2.0
Imaging databases store images. 1.4142135623730951
Imaging databases store images. Imaging databases store images. Imaging databases store images. 5.0990195135927845


In [123]:
X[4].toarray()

array([[0, 0, 0, 0, 3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        0, 0]])

In [124]:
X[3].toarray()

array([[0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0]])

In [126]:
def dist(v1, v2):
    v1_normalized = v1 / sp.linalg.norm(v1.toarray())
    v2_normalized = v2 / sp.linalg.norm(v2.toarray()) 
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())

In [127]:
for i in range(5):
    d = dist(X[i],new_post_vec)
    print(contents[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.414213562373095
Imaging databases can get huge. 0.8573732768944039
Most imaging databases safe images permanently. 0.9194016867619662
Imaging databases store images. 0.7653668647301795
Imaging databases store images. Imaging databases store images. Imaging databases store images. 0.7653668647301795


In [128]:
vectorizer.get_feature_names()

['about',
 'actually',
 'can',
 'contains',
 'databases',
 'get',
 'huge',
 'images',
 'imaging',
 'interesting',
 'is',
 'it',
 'learning',
 'machine',
 'most',
 'much',
 'not',
 'permanently',
 'post',
 'safe',
 'store',
 'stuff',
 'this',
 'toy']

In [130]:
vectorizer = CountVectorizer(stop_words='english') 
X = vectorizer.fit_transform(contents) 
vectorizer.get_feature_names()

['actually',
 'contains',
 'databases',
 'huge',
 'images',
 'imaging',
 'interesting',
 'learning',
 'machine',
 'permanently',
 'post',
 'safe',
 'store',
 'stuff',
 'toy']

In [131]:
X

<5x15 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [134]:
new_post_vec = vectorizer.transform([new_post])

In [135]:
for i in range(5):
    d = dist(X[i],new_post_vec)
    print(contents[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.414213562373095
Imaging databases can get huge. 0.6058108930553725
Most imaging databases safe images permanently. 0.8573732768944039
Imaging databases store images. 0.7653668647301795
Imaging databases store images. Imaging databases store images. Imaging databases store images. 0.7653668647301795


In [137]:
print(vectorizer.get_feature_names())

['actually', 'contains', 'databases', 'huge', 'images', 'imaging', 'interesting', 'learning', 'machine', 'permanently', 'post', 'safe', 'store', 'stuff', 'toy']


In [136]:
X[3].toarray()

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [140]:
import nltk.stem
s = nltk.stem.SnowballStemmer('english') 
s.stem('graphics')
#s.stem("imaging") 
#s.stem("image") 
#s.stem("imagination") 
#s.stem("imagine")

'graphic'

In [142]:
print(s.stem("imaging") )
print(s.stem("image") )
print(s.stem("imagination"))
print(s.stem("imagine"))

imag
imag
imagin
imagin


In [145]:
import nltk.stem
english_stemmer = nltk.stem.SnowballStemmer('english')

class StemmedCountVectorizer(CountVectorizer): 
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer() 
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [147]:
vectorizer = StemmedCountVectorizer(stop_words='english')
X = vectorizer.fit_transform(contents)

In [148]:
X

<5x14 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [149]:
print(vectorizer.get_feature_names())

['actual', 'contain', 'databas', 'huge', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'safe', 'store', 'stuff', 'toy']


In [150]:
new_post_vec = vectorizer.transform([new_post])

In [151]:
for i in range(5):
    d = dist(X[i],new_post_vec)
    print(contents[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.414213562373095
Imaging databases can get huge. 0.6058108930553725
Most imaging databases safe images permanently. 0.6296288974669553
Imaging databases store images. 0.5176380902050415
Imaging databases store images. Imaging databases store images. Imaging databases store images. 0.5176380902050415


# TF-IDF

In [152]:
a ,abb, abc =['a'],['a','b','b'],['a','b','c']

In [153]:
D = [a,abb,abc]

In [154]:
import math
# tfidf('a',a,D)
tf = 1/1
idf = math.log(3/3)
tf *idf

0.0

In [157]:
import math
# tfidf('a',abb,D)
tf = 1/3
idf = math.log(3/3)
tf *idf

0.0

In [158]:
import math
# tfidf('b',abb,D)
tf = 2/3
idf = math.log(3/2)
tf *idf

0.27031007207210955

In [161]:
def tfidf(t, d, D):
    tf = d.count(t)/len(d)
    idf = math.log(len(D)/len([doc for doc in D if t in doc]))
    return tf *idf

In [162]:
tfidf('c',abc,D)

0.3662040962227032

In [176]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [177]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(contents)

In [178]:
X

<5x24 sparse matrix of type '<class 'numpy.float64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [179]:
class StemmedTfidfVectorizer(TfidfVectorizer): 
    def build_analyzer(self):
        analyzer = super(TfidfVectorizer,self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [180]:
vectorizer = StemmedCountVectorizer(stop_words='english')
X = vectorizer.fit_transform(contents)

In [181]:
X

<5x14 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [182]:
new_post_vec = vectorizer.transform([new_post])

In [183]:
for i in range(5):
    d = dist(X[i],new_post_vec)
    print(contents[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.414213562373095
Imaging databases can get huge. 0.6058108930553725
Most imaging databases safe images permanently. 0.6296288974669553
Imaging databases store images. 0.5176380902050415
Imaging databases store images. Imaging databases store images. Imaging databases store images. 0.5176380902050415


# 中文詞頻矩陣

In [82]:
import jieba
ary = ['【更新】柯P:洪智坤洩漏公文案還沒看到公文 今處理',
        '留洪智坤 柯:殘障求職不易', 
       '人事處議處洪智坤 柯P:不清楚議處結果']


In [83]:
type(ary)

list

In [199]:
corpus = []

In [200]:
jieba.add_word('柯P')
jieba.add_word('人事處')
jieba.add_word('洪智坤')

In [201]:
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))

In [202]:
corpus

['【 更新 】 柯P : 洪智坤 洩漏 公文案 還 沒 看到 公文   今 處理',
 '留 洪智坤   柯 : 殘障 求職 不易',
 '人事處 議處 洪智坤   柯P : 不 清楚 議處 結果']